### ISSUE TITLE
Define Data Preparation Roadmap

### ISSUE THREAD

**Issue by Volscente** [Volscente/DruidicGroveAI#12]
# Description
As a Data Scientist,
I want to define the set of required data preparations steps,
In order to have a roadmap for the Data Preparation implementation phase.

# Changelog
- [x] Add Section `General` in Document `docs/stackoverflow_answer_score_classification/development_v.1.0.x.html`
- [x] Add Section `Input Tables` in Document `docs/stackoverflow_answer_score_classification/development_v.1.0.x.html`
- [x] Add Section `Data Preparation` in Document `docs/stackoverflow_answer_score_classification/development_v.1.0.x.html`
- [x] Add Section `Training Dataset` in Document `docs/stackoverflow_answer_score_classification/development_v.1.0.x.html`
- [x] Update Documentation
- [x] Update Wiki
- [x] Update `CHANGELOG.md`
- [x] Update `README.md`
- [x] Update project version
- [x] PR to dev
